n_layers : [1, 2]  # 1,2
learning_rate: [0.001]
reg_weight : [0.1, 0.01, 0.001]  # 0.1, 0.01, 0.001
ssl_alpha : [0.1,0.01,0.2,1]  # 0.1,0.01,0.2
ssl_temp : [0.1,0.2,0.5,1]  # 0.1,0.2,0.5

hyper_parameters: ["n_layers","learning_rate", "reg_weight","ssl_alpha","ssl_temp"]