n_layers : [1]
learning_rate: [0.1]
reg_weight : [0.01]  # 0.0001, 0.001, 0.01, 0.1
dropout : [0.1]  # 0.1, 0.2, 0.3, 0.4, 0.5
cl_weight : [2.0]  # 0.1, 0.5, 1.0, 1.5, 2.0

hyper_parameters: ["n_layers","learning_rate", "reg_weight", "dropout", 'cl_weight']