n_layers : [1, 2, 3]
learning_rate: [0.1, 0.01, 0.001, 0.0001]
reg_weight : [0.1, 0.01, 0.001, 0.0001]
dropout : [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
cl_weight : [0.1, 1.0, 2.0]

hyper_parameters: ["n_layers","learning_rate", "reg_weight", "dropout", 'cl_weight']