learning_rate: [0.001]
noise_scale : [0.001]  # 0.00001, 0.0001, 0.001, 0.01, 0.1
noise_min : [0.005]  # 0.0005, 0.001, 0.005
noise_max : [0.005]  # 0.005, 0.01
steps : [5]  # 2, 5, 10, 40, 50, 100
dims : ["[1000]"]  # '[300]', "[200,600]", "[1000]"

hyper_parameters: ["learning_rate","noise_scale", "noise_min", "noise_max", 'steps', 'dims']