learning_rate: [0.001]
reg_weight : [0.001]
n_layers : [2]
mm_layers : [1]
threshold : [0.1]
lambda_coeff : [0.6]

hyper_parameters: ["learning_rate", 'reg_weight', "mm_layers", "n_layers", 'threshold', 'lambda_coeff']