learning_rate: [0.001]
reg_weight : [0.1]  # 0.0001
n_layers : [3]  # 1,2,3
ssl_alpha : [0.01]  # 0.01, 0.1, 0.001
threshold : [0]  # -0.2, -0.1, 0, 0.1, 0.2
ssl_temp : [0.2]  # 0.1, 0.2, 0.5

hyper_parameters: ["learning_rate", 'reg_weight', "ssl_alpha", "n_layers", 'threshold', 'ssl_temp']