learning_rate: [0.1, 0.01, 0.001, 0.0001]
reg_weight : [0.1, 0.01, 0.001, 0.0001]
corDecay : [0.1, 0.01, 0.001, 0.0001]
n_factors : [2, 4, 8]
n_iterations : [1, 2, 3]
n_layers : [1, 2, 3]

hyper_parameters: ["n_layers","learning_rate", "reg_weight", "corDecay", 'n_factors', 'n_iterations']