n_layers : [1]
learning_rate: [0.001]
reg_weight : [0.001, 0.0001, 0.00001]  # 0.001, 0.0001, 0.00001
dropout : [0, 0.1, 0.2]  # 0, 0.1, 0.2

hyper_parameters: ["n_layers","learning_rate", "reg_weight", "dropout"]