learning_rate: [0.001]
reg_weight : [0.1, 0.01, 0.001, 0.0001, 0.00001]  # 0.1, 0.01, 0.001, 0.0001, 0.00001
n_layers : [1]
e_loss : [1, 0.5, 0.1, 0.01, 0.001]  # lambda0: 1, 0.5, 0.1, 0.01, 0.001
ssl_alpha : [0.01]  # lambda1:  1, 0.1, 0.01
ris_lambda : [0.5]  # 𝜔: 0.1, 0.25, 0.5, 0.75, 1
ssl_temp : [0.1]  # 𝜏: 0.1, 0.5, 1
rebuild_k : [1]

hyper_parameters: ["e_loss","learning_rate", "reg_weight", "ssl_alpha", 'ris_lambda', 'ssl_temp', 'rebuild_k']