learning_rate: [0.001]
reg_weight : [0.01]
n_layers : [2]
uu_topk : [40]
ii_topk : [10]
lambda_coeff : [0.6]

hyper_parameters: ["n_layers","learning_rate", "reg_weight", "uu_topk", 'ii_topk', 'lambda_coeff']