n_layers : [3]
learning_rate: [0.001]
reg_weight : [1]  # 0.1, 0.01, 0.001
node_dropout : [0]  # 0.0, 0.1, 0.2, 0.3
message_dropout : [0]  # 0.0, 0.1, 0.2, 0.3
grid_size : [1]  # 1, 2, 4, 8

hyper_parameters: ["n_layers","learning_rate", "reg_weight", "node_dropout", "message_dropout", "grid_size"]