n_layers : [3]
learning_rate: [0.001]
reg_weight : [0.00001]
ssl_alpha : [0.5]  # 0.01, 0.05, 0.1, 0.5, 1.0
ssl_temp : [0.5]
leaky : [0.5]  # 1.0, 0.5, 0.1
keepRate : [0.75]  # 0.25, 0.5, 0.75, 1.0
mult : [0.01]

hyper_parameters: ["n_layers","learning_rate", "reg_weight","ssl_alpha","ssl_temp", "leaky", "keepRate", "mult"]