n_layers : [2]
learning_rate: [0.001]
reg_weight : [0, 0.0000001]  # 0, 0.0000001
ssl_alpha : [0.01]  # 0.01, 0.1, 0.2, 0.5
ssl_temp : [0.1]  # 0.1, 0.2, 0.5

hyper_parameters: ["n_layers","learning_rate", "reg_weight","ssl_alpha","ssl_temp"]