learning_rate: [0.0001]
reg_weight : [0.001]
mm_layers : [1]
dropout : [0.1]  # 0.1, 0.2, 0.3, 0.4, 0.5
ssl_temp : [0.2]  # 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8
align_weight: [0.1]  # 0.1, 0.2, 0.3
mask_weight_g: [0.001]  # 0.0001, 0.001, 0.01
mask_weight_f: [1.5]  # 0.5, 1, 1.5, 2, 2.5

hyper_parameters: ["learning_rate", "reg_weight", "dropout", 'ssl_temp', 'align_weight', 'mask_weight_g', 'mask_weight_f']