learning_rate: [0.01]
reg_weight : [0.1]
n_layers : [5]
ssl_alpha : [0.1]  # 0.01, 0.1, 0.5
ssl_temp : [0.2]  # 0.1, 0.2, 0.3

hyper_parameters: ["learning_rate", "ssl_alpha", "n_layers", 'ssl_temp', 'reg_weight']