learning_rate: [0.001]
reg_weight : [0.0001]  # 0.01, 0.001, 0.0001
n_layers : [6]
h_layers : [2]
uu_topk : [10]  # 1,5,10
ii_topk : [10]  # 1,5,10
num_hypernodes : [10]  # 2, 5, 10
ssl_alpha : [0.01]  # lambda1:  1, 0.1, 0.01
ssl_temp : [0.1]  # ğœ: 0.1, 0.2, 0.5
beta1: [1]  # 0.1, 0.5, 1
beta2: [0.5]  # 0.1, 0.5, 1

hyper_parameters: ["n_layers", "h_layers", "learning_rate", "reg_weight", "uu_topk", 'ii_topk', 'num_hypernodes',
                   'ssl_alpha', 'ssl_temp', 'beta1', 'beta2']
