learning_rate: [0.1, 0.01, 0.001, 0.0001]
reg_weight : [0.1, 0.01, 0.001, 0.0001]
n_layers : [1, 2, 3]
mm_layers : [1, 2, 3]
ii_topk : [5, 10, 20]
ssl_temp : [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
ssl_alpha : [0.01, 0.05, 0.1, 0.5, 1.0]
lambda_coeff : [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

hyper_parameters: ["n_layers","learning_rate", "reg_weight", "mm_layers", 'ii_topk', 'lambda_coeff', "ssl_temp", "ssl_alpha"]