learning_rate: [0.001]  # 0.01, 0.001, 0.0001
reg_weight : [0.001]
n_layers : [3]
ssl_alpha : [0.4]
ssl_temp : [0.2]
dropout : [0.1]

hyper_parameters: ["learning_rate", "ssl_alpha", 'ssl_temp', 'reg_weight']