learning_rate: [0.01]
reg_weight : [0.001]
n_layers : [2]
ssl_alpha : [0.001]
ssl_temp : [0.1]
ae_weight : [1.0]

hyper_parameters: ["learning_rate", "ssl_alpha", "n_layers", 'ssl_temp', 'ae_weight', 'reg_weight']