learning_rate: [0.001]
reg_weight : [0.1, 1]
n_layers : [4]
neg_weight : [0.001, 0.01, 0.1, 1]
dropout : [0.1]
prompt_num : [1, 2, 3, 4, 5]  # 1, 2, 3, 4, 5

hyper_parameters: ['prompt_num', "dropout", "neg_weight", "learning_rate", "reg_weight"]