n_layers : [3]
learning_rate: [0.001]
reg_weight : [0.0001] # 0.1, 0.01, 0.001, 0.0001
ssl_alpha : [0.01]  # 0.01, 0.1, 0.2
ssl_temp : [0.2]  # 0.1, 0.2, 0.5

hyper_parameters: ["n_layers","learning_rate", "reg_weight","ssl_alpha","ssl_temp"]