learning_rate: [0.001]
ssl_alpha : [0.01] # 0.01, 0.05, 0.1, 0.5, 1.0
n_layers : [2] # 1,2,3
ssl_temp : [0.2] # 0.1, 0.2, 0.5, 1.0

hyper_parameters: ["learning_rate", "ssl_alpha", "n_layers", 'ssl_temp']