learning_rate: [0.1, 0.01, 0.001, 0.0001]
ssl_alpha : [0.01, 0.05, 0.1, 0.5, 1.0]
n_layers : [1, 2, 3]
ssl_temp : [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

hyper_parameters: ["learning_rate", "ssl_alpha", "n_layers", 'ssl_temp']